ADDR_TORQUE_ENABLE = 64
ADDR_GOAL_POSITION = 116
LEN_GOAL_POSITION = 4  # Data Byte Length
ADDR_PRESENT_POSITION = 132
LEN_PRESENT_POSITION = 4  # Data Byte Length
DXL_MINIMUM_POSITION_VALUE = 2000  # min=0
DXL_MAXIMUM_POSITION_VALUE = 2200  # max=4095
BAUDRATE = 1000000
ADDR_PRO_PROFILE_VELOCITY = 112
ADDR_PRO_PROFILE_ACCELERATION = 108
PROTOCOL_VERSION = 2.0

DXL1_ID = 1
DXL2_ID = 2
DEVICENAME = '/dev/ttyUSB0'

TORQUE_ENABLE = 1
TORQUE_DISABLE = 0
DXL_MOVING_STATUS_THRESHOLD = 20
